######################################################################
# Automatically generated by qmake (3.0) ?? ?? 25 21:42:44 2016
######################################################################

QT       += core gui
QT       += serialport

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets
TEMPLATE = app
TARGET = BasicTransceiver
INCLUDEPATH += .

# Input
HEADERS += basictransceiver.h
FORMS += \
    basictransceiver.ui
SOURCES += basictransceiver.cpp main.cpp

RESOURCES += \
    basictransceiver.qrc

RC_ICONS = basic_transceiver.ico
